### ISSUE TITLE
Stuck on your payment is being validated

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash-2#200]
```
core.js:6014 ERROR TypeError: Cannot read property 'active' of null
    at SafeSubscriber._next (payment-validation.component.ts:22)
```

Steps to reproduce: Upgrade a plan and when modal comes up error keeps on repeating.

**Comment by Alir3z4** [comment]
One thing to note here, I got an error report about this on the backend for draft (_draft once a while gives annoying error for random endpoint and not particularly payment endpoints. _).
This could be because backend never gave you the thing you wanted.

In any case, such problem should occur when waiting for backend flag, it could even take hours to be notified about the successful payment, if you don't get anything from backend after 15 seconds, just let the user know "Thank you for upgrading, once we the payment confirmed, you blog will be upgraded." and then return them to what ever you need to go.

**Comment by ArsalanSavand** [comment]
@Alir3z4 I agree, I was waiting for the payment validation for like 5 minutes and nothing happend. This issue only happens in staging I guess.
So after that 5 minutes, I was just browsing dashboard, then I saw I was upgraded after a while.

**Comment by ArsalanSavand** [comment]
What's the final decision here?
Should I remove the payment validation modal?

**Comment by Alir3z4** [comment]
No, keep the payment validation modal for sure.

If after maximum of 1 minute nothing happened, redirect the user to dashboard and write

> Thank you for upgrading, once the payment confirmed, your blog will be upgraded.
